FROM ubuntu:22.04-slim

WORKDIR /usr/src/app

# 安裝必要的工具並添加 PPA
RUN apt update && apt-get install --no-install-recommends -y software-properties-common gnupg2 \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/* \
    && add-apt-repository ppa:pipewire-debian/pipewire-upstream

# 安裝 Pipewire，請將 <版本號> 替換為實際版本號
RUN apt update && apt-get install --no-install-recommends -y pipewire=0.3.48 libspa-0.2-modules=0.3.48-1ubuntu1 \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

RUN pipewire --version
RUN systemctl --user status pipewire || true

# 如果有應用程式啟動命令，可以添加到這裡
CMD ["bash"]