name: audio_control

services:
  audio_ctl:
    build:
      context: .
      dockerfile: ./Dockerfile_ctl

    image: ${DOCKER_HUB_SERVER}/${DOCKER_PROJECT}/audio-ctl:${TAGVERSION}
    container_name: audio-ctl

    command: ["python", "audio_control.py"]
    ports:
      - "5003:5003"
    devices:
      - /dev/bus/usb:/dev/bus/usb
    volumes:
      - /run/user/1000/pulse:/run/user/1000/pulse
      - /var/run/docker.sock:/var/run/docker.sock
      - ./docker-compose_services.yml:/usr/src/app/docker-compose_services.yml
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    environment:
      - PULSE_SERVER=unix:/run/user/1000/pulse/native
      - TZ=Asia/Taipei
    restart: unless-stopped